name: PHPUnit tests

on:
  push:
    branches-ignore:
      - dev
      - master

jobs:
  tests:
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      APP_KEY: ${{ secrets.APP_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      APP_DEBUG: true
      DB_DATABASE: db
      DB_USER: root
      DB_PASSWORD: root

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Rum migrations
        run: php artisan migrate:fresh --seed --no-interaction

      - name: Run PHPUnit
        run: php8.0 vendor/bin/phpunit

      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logs
          path: storage/logs/laravel.log
